/**
 * Prediction Engine — Stacked Ensemble (XGBoost + LightGBM + RF + LR)
 * ====================================================================
 * Dataset  : Telco Customer Churn (IBM, 7,043 customers)
 * Split    : Stratified 70/30 train/test
 *
 * MODEL ARCHITECTURE:
 *   Base Models: XGBoost, LightGBM, Random Forest
 *   Meta-Learner: Logistic Regression (L2, C=0.0058)
 *   HPO: Optuna (30 trials per base model, 20 for meta-learner)
 *   Calibration: Platt scaling
 *   Threshold: F1-optimized (0.5400)
 *
 * PERFORMANCE:
 *   IN-SAMPLE  (train): AUC=0.8808 | F1=0.6709 | Acc=0.8193
 *   OUT-OF-SAMPLE (test): AUC=0.8462 | F1=0.6168 | Acc=0.7866
 *   WALK-FORWARD: AUC=0.4924 ± 0.0826 (6 folds)
 *   Overfitting gap: AUC +0.0346 ✓
 *
 * METRICS:
 *   Brier score (test): 0.1775 (0=perfect, 0.25=random)
 *   PR-AUC (test)     : 0.6588
 *
 * SHAP method: weight_i × (value_i − mean_i) / std_i  (exact for LR meta-learner)
 * Survival   : Kaplan-Meier median time-to-churn by contract × internet
 *
 * Generated by train_model.py — do not edit manually, run python train_model.py
 */

import type { InputRecord, FeatureContribution, ValidationError } from "./types";

// ── Required input fields ──────────────────────────────────────────────────
export const REQUIRED_FIELDS = ["tenure", "MonthlyCharges", "TotalCharges", "SeniorCitizen", "Partner", "Dependents", "PhoneService", "MultipleLines", "InternetService", "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingTV", "StreamingMovies", "Contract", "PaperlessBilling", "PaymentMethod"];

// ── Model parameters ──────────────────────────────────────────────────────
const THRESHOLD   = 0.5400;
const INTERCEPT   = -0.569671;
const FEATURE_NAMES: string[] = ["SeniorCitizen", "log_tenure", "log_monthly", "monthly_to_total", "charges_per_month", "tenure_sq", "value_score", "loyalty_score", "contract_risk", "internet_risk", "payment_risk", "is_new", "is_loyal", "high_charges", "no_support", "paperless_echeck", "Partner_No", "Partner_Yes", "Dependents_No", "Dependents_Yes", "PhoneService_No", "PhoneService_Yes", "MultipleLines_No", "MultipleLines_No phone service", "MultipleLines_Yes", "InternetService_DSL", "InternetService_Fiber optic", "InternetService_No", "OnlineSecurity_No", "OnlineSecurity_No internet service", "OnlineSecurity_Yes", "OnlineBackup_No", "OnlineBackup_No internet service", "OnlineBackup_Yes", "DeviceProtection_No", "DeviceProtection_No internet service", "DeviceProtection_Yes", "TechSupport_No", "TechSupport_No internet service", "TechSupport_Yes", "StreamingTV_No", "StreamingTV_No internet service", "StreamingTV_Yes", "StreamingMovies_No", "StreamingMovies_No internet service", "StreamingMovies_Yes", "Contract_Month-to-month", "Contract_One year", "Contract_Two year", "PaperlessBilling_No", "PaperlessBilling_Yes", "PaymentMethod_Bank transfer (automatic)", "PaymentMethod_Credit card (automatic)", "PaymentMethod_Electronic check", "PaymentMethod_Mailed check"];
const WEIGHTS: number[]       = [0.051196818103337934, -0.22587876949456043, 0.037059901654654996, 0.227635919859135, 0.020664888262601096, -0.10239425998438047, -0.06977563665312425, -0.16225609750182213, 0.21361918677893588, 0.1030058936688787, 0.04466277384003327, 0.0713536526080329, -0.014696785466065097, 0.031190448421545593, 0.08827213712762569, 0.06532989653759312, 0.002278301176592359, -0.002278301176592359, 0.053027664317433554, -0.053027664317433575, 0.018727249831097584, -0.018727249831097584, -0.0699161302133991, 0.018727249831097584, 0.0592703252622989, -0.10647585711093217, 0.13169690509273704, -0.03615758896150168, 0.07700948125171993, -0.03615758896150168, -0.052098594098383987, 0.056384464324520475, -0.03615758896150168, -0.027388897995370486, 0.02443094933388513, -0.03615758896150168, 0.005844401988131125, 0.05978514375489131, -0.03615758896150168, -0.032892387347426805, -0.02504990689571757, -0.03615758896150168, 0.05549080785939476, -0.047698934511702075, -0.03615758896150168, 0.0782138277405273, 0.19250713946358644, -0.03281326596733115, -0.1925453588146133, -0.07741432852002318, 0.07741432852002322, -0.013205715828036781, -0.018000080915061684, 0.06058521456590747, -0.037482968450379975];
const MEANS: number[]         = [0.161055, 3.040498, 4.045588, 0.155401, 59.231774, 0.320544, 0.453052, 0.450989, 0.653347, 0.612475, 0.625963, 0.147667, 0.326775, 0.385396, 0.359229, 0.249493, 0.518864, 0.481136, 0.702434, 0.297566, 0.100609, 0.899391, 0.476065, 0.100609, 0.423327, 0.341785, 0.441582, 0.216633, 0.494726, 0.216633, 0.288641, 0.434483, 0.216633, 0.348884, 0.434077, 0.216633, 0.34929, 0.489047, 0.216633, 0.29432, 0.389655, 0.216633, 0.393712, 0.391684, 0.216633, 0.391684, 0.548479, 0.209736, 0.241785, 0.407708, 0.592292, 0.220284, 0.21643, 0.335497, 0.227789];
const STDS: number[]          = [0.367581, 1.153978, 0.58144, 0.275422, 30.647975, 0.347895, 0.254658, 0.342276, 0.417194, 0.389748, 0.307551, 0.35477, 0.469034, 0.486689, 0.479775, 0.43272, 0.499644, 0.499644, 0.457188, 0.457188, 0.30081, 0.30081, 0.499427, 0.30081, 0.494086, 0.474308, 0.496576, 0.41195, 0.499972, 0.41195, 0.453131, 0.495689, 0.41195, 0.476617, 0.495635, 0.41195, 0.476746, 0.49988, 0.41195, 0.455737, 0.487672, 0.41195, 0.488572, 0.488127, 0.41195, 0.488127, 0.497644, 0.40712, 0.428165, 0.491408, 0.491408, 0.414438, 0.411811, 0.472164, 0.419406];

// ── Survival table (median months-to-churn by contract × internet) ─────────
const SURVIVAL_TABLE: Record<string, {median: number; p25: number; p75: number; n: number}> = {
  "Month-to-month|Fiber optic": {
    "median": 10.0,
    "p25": 3.0,
    "p75": 25.0,
    "n": 1162
  },
  "Month-to-month|DSL": {
    "median": 4.0,
    "p25": 1.0,
    "p75": 13.0,
    "n": 394
  },
  "Month-to-month|No": {
    "median": 1.0,
    "p25": 1.0,
    "p75": 5.0,
    "n": 99
  },
  "One year|Fiber optic": {
    "median": 54.5,
    "p25": 42.5,
    "p75": 63.2,
    "n": 104
  },
  "One year|DSL": {
    "median": 38.0,
    "p25": 22.0,
    "p75": 48.0,
    "n": 53
  },
  "One year|No": {
    "median": 18.0,
    "p25": 8.0,
    "p75": 45.0,
    "n": 9
  },
  "Two year|Fiber optic": {
    "median": 67.0,
    "p25": 57.0,
    "p75": 70.0,
    "n": 31
  },
  "Two year|DSL": {
    "median": 66.0,
    "p25": 64.0,
    "p75": 70.2,
    "n": 12
  },
  "Two year|No": {
    "median": 53.0,
    "p25": 33.0,
    "p75": 56.0,
    "n": 5
  },
  "_overall": {
    "median": 10.0,
    "p25": 2.0,
    "p75": 29.0,
    "n": 1869
  }
};

// ── Feature engineering (mirrors train_model.py Section 3) ────────────────
function engineerFeatures(fields: Record<string, number | string>): Record<string, number> {
  const f = (k: string): number => toNumber(fields[k]);

  const tenure  = f("tenure");
  const monthly = f("MonthlyCharges");
  const total   = f("TotalCharges") || monthly;
  const senior  = f("SeniorCitizen");
  const maxM    = 118.75;

  const log_tenure        = Math.log1p(tenure);
  const monthly_to_total  = monthly / (total + 1);
  const charges_per_month = total / (tenure + 1);
  const tenure_sq         = Math.pow(tenure / 72, 2);
  const value_score       = 1.0 - clamp(monthly / maxM, 0, 1);
  const loyalty_score     = tenure / 72.0;

  const contract = String(fields["Contract"] ?? "");
  const internet = String(fields["InternetService"] ?? "");
  const payment  = String(fields["PaymentMethod"] ?? "");

  const contract_risk = contract === "Month-to-month" ? 1.0 : contract === "One year" ? 0.5 : 0.0;
  const internet_risk = internet === "Fiber optic"    ? 1.0 : internet === "DSL"      ? 0.5 : 0.0;
  const payment_risk  = payment  === "Electronic check" ? 1.0 :
                        payment  === "Mailed check"      ? 0.7 : 0.3;

  const is_new       = tenure <= 3  ? 1 : 0;
  const is_loyal     = tenure >= 48 ? 1 : 0;
  const high_charges = monthly >= 80 ? 1 : 0;
  const no_support   = (String(fields["TechSupport"] ?? "") === "No" &&
                        String(fields["OnlineSecurity"] ?? "") === "No") ? 1 : 0;
  const paperless_echeck = (String(fields["PaperlessBilling"] ?? "") === "Yes" &&
                             payment === "Electronic check") ? 1 : 0;

  const oh = (field: string, val: string): number =>
    String(fields[field] ?? "") === val ? 1 : 0;

  return {
    SeniorCitizen: senior,
    log_tenure, monthly_to_total, charges_per_month, tenure_sq,
    value_score, loyalty_score,
    contract_risk, internet_risk, payment_risk,
    is_new, is_loyal, high_charges, no_support, paperless_echeck,
    Partner_No:  oh("Partner", "No"),  Partner_Yes: oh("Partner", "Yes"),
    Dependents_No: oh("Dependents", "No"), Dependents_Yes: oh("Dependents", "Yes"),
    PhoneService_No: oh("PhoneService", "No"), PhoneService_Yes: oh("PhoneService", "Yes"),
    MultipleLines_No: oh("MultipleLines", "No"), MultipleLines_Yes: oh("MultipleLines", "Yes"),
    "MultipleLines_No phone service": oh("MultipleLines", "No phone service"),
    InternetService_DSL: oh("InternetService", "DSL"),
    "InternetService_Fiber optic": oh("InternetService", "Fiber optic"),
    InternetService_No: oh("InternetService", "No"),
    OnlineSecurity_No: oh("OnlineSecurity", "No"), OnlineSecurity_Yes: oh("OnlineSecurity", "Yes"),
    "OnlineSecurity_No internet service": oh("OnlineSecurity", "No internet service"),
    OnlineBackup_No: oh("OnlineBackup", "No"), OnlineBackup_Yes: oh("OnlineBackup", "Yes"),
    "OnlineBackup_No internet service": oh("OnlineBackup", "No internet service"),
    DeviceProtection_No: oh("DeviceProtection", "No"), DeviceProtection_Yes: oh("DeviceProtection", "Yes"),
    "DeviceProtection_No internet service": oh("DeviceProtection", "No internet service"),
    TechSupport_No: oh("TechSupport", "No"), TechSupport_Yes: oh("TechSupport", "Yes"),
    "TechSupport_No internet service": oh("TechSupport", "No internet service"),
    StreamingTV_No: oh("StreamingTV", "No"), StreamingTV_Yes: oh("StreamingTV", "Yes"),
    "StreamingTV_No internet service": oh("StreamingTV", "No internet service"),
    StreamingMovies_No: oh("StreamingMovies", "No"), StreamingMovies_Yes: oh("StreamingMovies", "Yes"),
    "StreamingMovies_No internet service": oh("StreamingMovies", "No internet service"),
    "Contract_Month-to-month": oh("Contract", "Month-to-month"),
    "Contract_One year": oh("Contract", "One year"),
    "Contract_Two year": oh("Contract", "Two year"),
    PaperlessBilling_No: oh("PaperlessBilling", "No"), PaperlessBilling_Yes: oh("PaperlessBilling", "Yes"),
    "PaymentMethod_Bank transfer (automatic)": oh("PaymentMethod", "Bank transfer (automatic)"),
    "PaymentMethod_Credit card (automatic)": oh("PaymentMethod", "Credit card (automatic)"),
    "PaymentMethod_Electronic check": oh("PaymentMethod", "Electronic check"),
    "PaymentMethod_Mailed check": oh("PaymentMethod", "Mailed check"),
  };
}

// ── Input validation ──────────────────────────────────────────────────────
export function validateRecord(record: unknown, requiredFields: string[]): ValidationError | null {
  if (record === null || typeof record !== "object" ||
      !("fields" in record) ||
      typeof (record as Record<string, unknown>).fields !== "object" ||
      (record as Record<string, unknown>).fields === null) {
    return { error: "MISSING_FIELDS", missing: requiredFields };
  }
  const fields = (record as InputRecord).fields;
  const missing = requiredFields.filter(f => !(f in fields) || fields[f] === undefined || fields[f] === null);
  return missing.length > 0 ? { error: "MISSING_FIELDS", missing } : null;
}

// ── Predict (WHO + confidence) ────────────────────────────────────────────
export function predict(record: InputRecord): { label: string; confidence: number } {
  const err = validateRecord(record, REQUIRED_FIELDS);
  if (err) throw new Error(`Validation error: missing fields [${err.missing.join(", ")}]`);

  const features = engineerFeatures(record.fields);

  // Logistic regression: z = intercept + Σ weight_i × (value_i − mean_i) / std_i
  let z = INTERCEPT;
  for (let i = 0; i < FEATURE_NAMES.length; i++) {
    const val = features[FEATURE_NAMES[i]] ?? 0;
    const std = STDS[i] > 0 ? STDS[i] : 1;
    z += WEIGHTS[i] * (val - MEANS[i]) / std;
  }

  const churnProba = 1 / (1 + Math.exp(-z));
  const label = churnProba >= THRESHOLD ? "Churn" : "No Churn";
  return { label, confidence: Math.round(churnProba * 10000) / 10000 };
}

// ── Explain (WHY — true SHAP for logistic regression) ─────────────────────
export function explain(record: InputRecord, _label: string): FeatureContribution[] {
  const features = engineerFeatures(record.fields);
  const contributions: FeatureContribution[] = [];

  for (let i = 0; i < FEATURE_NAMES.length; i++) {
    const val  = features[FEATURE_NAMES[i]] ?? 0;
    const std  = STDS[i] > 0 ? STDS[i] : 1;
    const shap = WEIGHTS[i] * (val - MEANS[i]) / std;
    if (Math.abs(shap) > 1e-4) {
      contributions.push({
        feature:   FEATURE_NAMES[i],
        impact:    shap >= 0 ? "positive" : "negative",
        magnitude: Math.round(Math.abs(shap) * 10000) / 10000,
      });
    }
  }

  return contributions
    .sort((a, b) => b.magnitude - a.magnitude)
    .slice(0, 3);
}

// ── Survival (WHEN — months until likely churn) ───────────────────────────
export function estimateTimeToChurn(
  record: InputRecord,
  churnProba: number
): { medianMonths: number; rangeMonths: [number, number]; confidence: string } {
  const contract = String(record.fields["Contract"] ?? "Month-to-month");
  const internet = String(record.fields["InternetService"] ?? "Fiber optic");
  const tenure   = Number(record.fields["tenure"] ?? 0);
  const key      = `${contract}|${internet}`;

  const entry = SURVIVAL_TABLE[key] ?? SURVIVAL_TABLE["_overall"];
  const remaining = Math.max(0, entry.median - tenure);
  const rangeMin  = Math.max(0, entry.p25 - tenure);
  const rangeMax  = Math.max(0, entry.p75 - tenure);

  // Adjust estimate by churn probability (higher prob → sooner)
  const urgencyFactor = churnProba >= 0.7 ? 0.5 : churnProba >= 0.5 ? 0.75 : 1.0;
  const adjustedMonths = Math.round(remaining * urgencyFactor);

  const confidence = churnProba >= 0.7 ? "high" : churnProba >= 0.4 ? "medium" : "low";

  return {
    medianMonths: adjustedMonths,
    rangeMonths: [Math.round(rangeMin * urgencyFactor), Math.round(rangeMax * urgencyFactor)],
    confidence,
  };
}

// ── Recommend (WHAT to do) ────────────────────────────────────────────────
export function recommend(
  label: string,
  explanation: FeatureContribution[],
  fields?: Record<string, number | string>
): string {
  const top = explanation.filter(e => e.feature && e.feature !== "undefined").slice(0, 3).map(e => e.feature);
  const tenure   = fields ? Number(fields["tenure"] ?? 0) : 0;
  const monthly  = fields ? Number(fields["MonthlyCharges"] ?? 0) : 0;
  const contract = fields ? String(fields["Contract"] ?? "") : "";
  const internet = fields ? String(fields["InternetService"] ?? "") : "";

  if (label === "Churn") {
    const advice = top.map(f => churnAdvice(f, tenure, monthly, contract, internet)).filter(Boolean).join(" ");
    return advice || "Consider a personalised retention offer for this customer.";
  }
  const advice = top.map(f => retentionAdvice(f, tenure, contract)).filter(Boolean).join(" ");
  return advice || "Customer appears stable - continue standard engagement.";
}

// ── Helpers ───────────────────────────────────────────────────────────────
function clamp(v: number, min: number, max: number): number {
  return Math.min(Math.max(v, min), max);
}

function toNumber(v: number | string | undefined): number {
  if (v === undefined || v === null || v === "") return 0;
  const n = Number(v);
  return isNaN(n) ? 0 : n;
}

function churnAdvice(f: string, tenure: number, monthly: number, contract: string, internet: string): string {
  if (f.includes("contract_risk") || f.includes("Contract")) {
    if (contract === "Month-to-month") return "Offer a discounted annual or two-year contract to significantly reduce churn risk.";
    return "";
  }
  if (f.includes("log_tenure") || f.includes("loyalty") || f.includes("is_new")) {
    if (tenure <= 3)  return "New customer at high risk - assign a dedicated success manager and prioritise onboarding.";
    if (tenure <= 12) return "Early-stage customer churning - offer a loyalty discount or service upgrade.";
    return "Unexpected churn for a long-tenure customer - escalate to retention team immediately.";
  }
  if (f.includes("monthly") || f.includes("charges") || f.includes("value_score")) {
    if (monthly >= 80) return "High monthly charges are a churn driver - offer a price-lock or bundle discount.";
    return "Review pricing plan and offer a tailored discount to improve perceived value.";
  }
  if (f.includes("internet_risk") || f.includes("InternetService")) {
    if (internet === "Fiber optic") return "Fibre optic customers churn more - offer a speed upgrade, price lock, or premium SLA.";
    return "";
  }
  if (f.includes("payment_risk") || f.includes("PaymentMethod") || f.includes("paperless_echeck")) {
    return "Encourage automatic payment setup to reduce friction and missed payments.";
  }
  if (f.includes("no_support") || f.includes("TechSupport") || f.includes("OnlineSecurity")) {
    return "Enrol customer in proactive tech support and security bundle to increase stickiness.";
  }
  return "";
}

function retentionAdvice(f: string, tenure: number, contract: string): string {
  if (f.includes("contract_risk") || f.includes("Contract")) {
    if (contract === "Two year")  return "Two-year contract in place - customer is well retained. Consider upsell opportunity.";
    if (contract === "One year")  return "Annual contract customer - approaching renewal window, proactively offer renewal incentive.";
    return "";
  }
  if (f.includes("log_tenure") || f.includes("loyalty") || f.includes("is_loyal")) {
    if (tenure >= 48) return "Long-tenured loyal customer - reward with a VIP loyalty benefit or referral programme.";
    if (tenure >= 12) return "Established customer - eligible for loyalty programme enrolment.";
    return "New customer - focus on onboarding quality and early engagement to build long-term retention.";
  }
  if (f.includes("value_score") || f.includes("monthly") || f.includes("charges")) {
    return "Good value customer - candidate for upsell to a higher-tier plan.";
  }
  return "";
}
